{% set name = "pyrfr" %}
{% set version = "0.8.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: cdc92b6054a351b85cc7496a2fc86e3192a9d04a92fd6bfa4aa629af360a6d1d

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('cxx') }}
    - doxygen
    - swig >3.0.3
  host:
    - pip
    - python
  run:
    - python

test:
  imports:
    - pyrfr
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/pyrfr/
  license: BSD-2-Clause AND BSD-3-Clause AND BSL-1.0 AND JSON AND MIT
  license_file:
    - include/cereal/external/rapidxml/license.txt
    - LICENSE_cereal-1.2.2
    - LICENSE_doxy2swig
    - LICENSE.txt
    - LICENSE_rapidjson
    - LICENSE_rapidxml
  summary: A extensible C++ library for random forests with Python bindings.
  dev_url: https://github.com/automl/random_forest_run

extra:
  recipe-maintainers:
    - BastianZim
    - mfeurer
